### ISSUE TITLE
Meta: Issues and limitations of WPT test importer

### ISSUE THREAD

**Issue by AtkinsSJ** [LadybirdBrowser/ladybird#2282]
`Meta/WPT.sh import foo` can import WPT tests directly into our own test suite, adapting them to our test runner. This is done in [`Meta/import-wpt-test.py`](https://github.com/LadybirdBrowser/ladybird/blob/master/Meta/import-wpt-test.py). However, this has some limitations; this issue keeps track of them.

- [ ] [Crash tests](https://web-platform-tests.org/writing-tests/crashtest.html) are not supported. We import them as text tests, and they always time out. We probably need a separate test category for crash tests.
- [ ] We don't handle links to images or other media files. They're not downloaded, and we may need to rewrite the URLs too.
- [ ] Importing async text tests does not work. This is probably not possible to solve, but listed here for completeness.

**Comment by shlyakpavel** [comment]
Related: https://github.com/LadybirdBrowser/ladybird/pull/2929

**Comment by Psychpsyo** [comment]
http://wpt.live/css/css-contain/contain-layout-001.html is currently unimportable, I believe because its reference file is one folder up.

**Comment by AtkinsSJ** [comment]
New issue discovered when importing `html/rendering/non-replaced-elements/lists/lists-styles-quirks.html` from WPT: The import script tries to import the URL from CSS `@namespace` rules.

**Comment by AtkinsSJ** [comment]
New issue discovered: We try to import fragment-only URLs like `url(#foo)`, which should be possible to avoid.

**Comment by AtkinsSJ** [comment]
New issue:  Uses of the `idl_test()` function should import the idl files they refer to. eg, `idl_test(['gamepad'], ['html', 'dom'], /* ... */ );` needs to import `gamepad.idl`, `html.idl` and `dom.idl` from `https://wpt.live/interfaces/`
