### ISSUE TITLE
Tracking Issue: WhatWG issues opened by or tracked by Ladybird

### ISSUE THREAD

**Issue by ADKaster** [LadybirdBrowser/ladybird#771]
Open Spec issues:

### whatwg/html:
 
- [ ] Removal of implied document https://github.com/whatwg/html/issues/4980
  Algorithm: [HostEnqueuePromiseJob](https://html.spec.whatwg.org/multipage/webappapis.html#hostenqueuepromisejob)
  See: https://github.com/LadybirdBrowser/ladybird/blob/01ff3d428684c1f638cfd47fb451179e66a78dd5/Userland/Libraries/LibWeb/Bindings/MainThreadVM.cpp#L267-L270
    
- [ ] UA style for `<br>` and `<wbr>` https://github.com/whatwg/html/issues/2291
  Algorithm: https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3
  See: https://github.com/LadybirdBrowser/ladybird/blob/01ff3d428684c1f638cfd47fb451179e66a78dd5/Userland/Libraries/LibWeb/CSS/Default.css#L366-L371
  https://github.com/LadybirdBrowser/ladybird/blob/01ff3d428684c1f638cfd47fb451179e66a78dd5/Userland/Libraries/LibWeb/CSS/StyleComputer.cpp#L2352-L2356

- [ ] Aborting document load impact on descendant navigables https://github.com/whatwg/html/issues/9711
  Algorithm: abort a document and its descendants
  See: https://github.com/LadybirdBrowser/ladybird/blob/01ff3d428684c1f638cfd47fb451179e66a78dd5/Userland/Libraries/LibWeb/DOM/Document.cpp#L3323-L3328

### whatwg/console

- [ ] Warn if timer doesn't exist when logging time https://github.com/whatwg/console/issues/134
  Algorithm: timeLog https://console.spec.whatwg.org/#timelog
  See: https://github.com/LadybirdBrowser/ladybird/blob/01ff3d428684c1f638cfd47fb451179e66a78dd5/Userland/Libraries/LibJS/Console.cpp#L394-L403
  
  
---

Resolved Spec issues:

### whatwg/html

- [ ] Document destruction in navigables https://github.com/whatwg/html/pull/9907
  Algorithm: destroy a document https://html.spec.whatwg.org/multipage/document-lifecycle.html#destroy-a-document
  See: https://github.com/LadybirdBrowser/ladybird/blob/01ff3d428684c1f638cfd47fb451179e66a78dd5/Userland/Libraries/LibWeb/DOM/Document.cpp#L3210-L3212
  Resolved in Ladybird: NO

**Comment by ADKaster** [comment]
@sideshowbarker This is what I was kind of thinking of for some sort of tracking list. Do you have any thoughts on how to organize/gather this information? This first cut was done with some manual `git grep whatwg/html` and link following.

**Comment by sideshowbarker** [comment]
> @sideshowbarker This is what I was kind of thinking of for some sort of tracking list.

Thanks for putting it together

> Do you have any thoughts on how to organize/gather this information?

As far as how to organize it, I think that looks great

> This first cut was done with some manual `git grep whatwg/html` and link following.

So when I do that, I get a bigger list:

```
$ git grep "whatwg/html/issues"  \
    | perl -pe 's/^.+(https.+whatwg\/html\/issues\/[0-9]+).*$/\1/' | sort --version-sort | uniq
https://github.com/whatwg/html/issues/2291
https://github.com/whatwg/html/issues/3255
https://github.com/whatwg/html/issues/4792
https://github.com/whatwg/html/issues/4980
https://github.com/whatwg/html/issues/8534
https://github.com/whatwg/html/issues/9122
https://github.com/whatwg/html/issues/9148
https://github.com/whatwg/html/issues/9355
https://github.com/whatwg/html/issues/9690
https://github.com/whatwg/html/issues/9711
https://github.com/whatwg/html/issues/9767
https://github.com/whatwg/html/issues/9869
https://github.com/whatwg/html/issues/9923
https://github.com/whatwg/html/issues/9973
https://github.com/whatwg/html/issues/10019
https://github.com/whatwg/html/issues/10192
https://github.com/whatwg/html/issues/10232
https://github.com/whatwg/html/issues/10240
https://github.com/whatwg/html/issues/10261
```

But I guess you already went through that whole longer list, to filter it down to just the issues we want to take action on?

I addition to that, doing `git grep -i "spec bug"` seems to catch some that don’t have upstream issues raised yet —

```
$ git grep -i "spec bug" | rg -v "whatwg/[a-z]+/issues"
Userland/Libraries/LibJS/CyclicModule.cpp:    // NOTE: This is likely a spec bug, see https://matrixlogs.bakkot.com/WHATWG/2023-02-13#L1
Userland/Libraries/LibJS/CyclicModule.cpp:    // FIXME: This is likely a spec bug, see load_requested_modules.
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp:        // FIXME: spec bug, this should be set.
Userland/Libraries/LibJS/Runtime/Temporal/Duration.cpp:        // FIXME: spec bug, should be set
Userland/Libraries/LibJS/Runtime/Temporal/TimeZone.cpp:                //     FIXME: spec bug? shouldn't [[EpochNanoseconds]] just be called [[Nanoseconds]]?
Userland/Libraries/LibWeb/Crypto/SubtleCrypto.cpp:    // FIXME: Spec bug: link to https://webidl.spec.whatwg.org/#a-promise-rejected-with
Userland/Libraries/LibWeb/DOM/Document.cpp:        // FIXME: Why do we assume `creation_url` is non-empty here? Is this a spec bug?
Userland/Libraries/LibWeb/DOM/Document.cpp:        // FIXME: Why do we assume `top_level_creation_url` is non-empty here? Is this a spec bug?
Userland/Libraries/LibWeb/DOM/DocumentLoading.cpp:    //        default to an "about:blank" url. Is this a spec bug?
Userland/Libraries/LibWeb/HTML/BrowsingContext.cpp:    // FIXME: There appears to be no way to get a null URL here, so it might be a spec bug.
Userland/Libraries/LibWeb/HTML/HTMLImageElement.cpp:            // FIXME: Spec bug! `selected_pixel_density` can be undefined here, per the spec.
Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:                //        This might be a spec bug(?)
Userland/Libraries/LibWeb/Layout/FlexFormattingContext.cpp:        //       Spec bug: https://github.com/w3c/csswg-drafts/issues/2890
```
…(though I realize the first ones are maybe ES spec bugs)

…and that incidentally also shows: for catching WHATWG issues, I guess we need `git grep "whatwg/[a-z]\+/issues" or such:
```
$ git grep "whatwg/[a-z]\+/issues" | rg -v "whatwg/html" \
    | perl -pe 's/^.+(https.+whatwg\/[a-z]+\/issues\/[0-9]+).*$/\1/' | sort --version-sort | uniq
https://github.com/whatwg/console/issues/134
https://github.com/whatwg/dom/issues/221
https://github.com/whatwg/dom/issues/907
https://github.com/whatwg/dom/issues/1102
https://github.com/whatwg/encoding/issues/312
https://github.com/whatwg/fetch/issues/1035
```

**Comment by ADKaster** [comment]
> But I guess you already went through that whole longer list, to filter it down to just the issues we want to take action on?

On the contrary, I wrote down the details for the first 5 I found and then got bored, hoping that "there's surely a way to script this" :)

**Comment by sideshowbarker** [comment]
OK, if it seems like we have agreement on using the wiki for this, and you start a wiki page for this there — with a dump of the markdown for the subset already in the issue description — then, I can make time to add all the rest of the issues (following the format in the issue description).

**Comment by ADKaster** [comment]
I've transposed this data so far into a markdown file in https://github.com/LadybirdBrowser/ladybird/pull/893. It feels... incomplete, and hard to work with, but still better than a github issue.

**Comment by AtkinsSJ** [comment]
If a single document is awkward, what about just making each individual one its own GitHub issue, with a shared label?

**Comment by sideshowbarker** [comment]
> If a single document is awkward, what about just making each individual one its own GitHub issue, with a shared label?

I think that could work fine too. I plan on helping follow up on the related issues upstream, helping them get attention upstream (e.g., by being on the WHATNOT calls to discuss them), and I don’t have any strong opinions about how the project manages the tracking for them here.
